### ISSUE TITLE
Not working in safari

### ISSUE THREAD

**Issue by IrosTheBeggar** [jberg/butterchurn#11]
I'm having trouble getting butterchurn for mStream to work in Safari.  The console has this error: 

```
TypeError: null is not an object (evaluating 'this.gl.createFramebuffer')
```

**Comment by captbaritone** [comment]
As far as I know Safari does not support WebGL 2, which Butterchurn uses. Check out https://github.com/jberg/butterchurn/blob/master/src/isSupported.js which exports a function to detect if Buttefchurn is supported in a given browser. We use this in Webamp. You can see the usage here:  https://github.com/captbaritone/webamp/blob/master/js/index.js

**Comment by captbaritone** [comment]
@jberg: it might be worth documenting this utility. Also might be worth also doing this detection inside butterchurn itself and throwing a more informative error.

**Comment by IrosTheBeggar** [comment]
I figured it was something like that.  Does the https://butterchurnviz.com/ use an old version that's WebGL1 compatible?  It's working on safari for me

**Comment by jberg** [comment]
Hey @IrosTheBeggar , sorry I forgot to mention the lack of browser support.

Thanks for answering @captbaritone , gonna add a browser support section to the README. And yea, should probably have a better error hah

In terms of butterchurnviz.com , on unsupported browsers it redirects to: https://legacy.butterchurnviz.com/

The original version of butterchurn used webgl 1 and that is what is at the legacy subdomain.

I haven't created an NPM package for that one because there are a few roadblocks I would need to fixup:

- old version uses a custom three.js fork
- old version uses slightly different presets (and supports a lot less of them)
- old version has a different API and supports fewer options (like preset transitions / pixelRatio sizing)
- a few more smaller things

As of now I don't really plan on having a way to use the older version, sorry.
