### ISSUE TITLE
Upload own presets?

### ISSUE THREAD

**Issue by akaleeroy** [jberg/butterchurn#4]
I have been breeding [new presets](https://gfycat.com/EnchantedAmazingGalapagosdove) via <kbd>M</kbd>ashups for years now.
Sure would be nice to load those from a URL.

**Comment by jberg** [comment]
Hi Leeroy,

Thanks for the interest in Butterchurn.

Allowing users to watch local presets is definitely something I want to add in the future.  There is currently a problem getting the shader conversion working in javascript, which is why we are only offering a fixed set of presets.

Definitely hoping to fix this in the future though, I'll let you know when we are able to load local presets directly.

Thanks!

**Comment by jberg** [comment]
Hi again,

There is some progress.  On webamp.org, you can now load your own local directory or presets or drag presets into the renderer. These are converted to butterchurn format in the browser which has a few downsides. Its a bit slow and doesn't always work, but give it a try :D

We have also launched a collection at archive.org. Each item has a link that will load that preset into butterchurn by default on webamp: https://archive.org/details/milkdrops

**Comment by akaleeroy** [comment]
> doesn't always work, but give it a try

Works for some, but for many other playlists I get this bug in Chrome:

```
butterchurn.js:1342 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at a.value (butterchurn.js:1342)
    at Object.selectPreset (Milkdrop.js:210)
    at Object._handleDrop (Milkdrop.js:193)
value @ butterchurn.js:1342
selectPreset @ Milkdrop.js:210
_handleDrop @ Milkdrop.js:193
```

Should I create an issue or wait?

Eternal gratitude if you can help me figure out how to make this one work: 
[just-red-circle.zip :package:](https://github.com/jberg/butterchurn/files/2921375/just-red-circle.zip)

**Comment by jberg** [comment]
So I did some poking around with the converter to see what is causing the errors (sorry the console errors are so vague :-X). The issue seems to be with some of the HLSL. If you change `double3` to `float3` everything seems to compile and work.  I will look into fixing this in the future, but for now I think that should solve the issue, let me know.

[just-red-circle.milk.zip](https://github.com/jberg/butterchurn/files/2921557/just-red-circle.milk.zip)
